/**
 * Project Name:iotgp-cds
 * File Name:ConstantUtil.java
 * Package Name:cn.inovance.iotgp.cds.util
 * Date:2014-5-9上午9:18:45
 * Copyright (c) 2014, Shenzhen Inovance technology Co., Ltd  All Rights Reserved.
 *
 */

package cn.inovance.iotgp.common.status;

/**
 * ClassName:ConstantUtil 常量.
 * 
 * @author w1898
 * @version
 * @since JDK 1.7
 * @see
 */
public enum StatusEnum {

	/** redis_存储路径 */
	CONSTANT_REDSIS_PREFIX("bms:constanttablelist"),
	/**
	 * 账户类别.
	 * 
	 */
	ACCOUNT_IDENTITY("ACCOUNT_IDENTITY"),ACCOUNT_IDENTITY_SYSER("1"),
	ACCOUNT_IDENTITY_CUSTOMER("2"),
	
	/**
	 * 客户编号起始值
	 */
	DEFAULT_CUSTOMER_CODE("00000"),
	
	/**
	 * 采集设备型号.
	 * 
	 */
	CD_REGISTERT_CODE_MODEL("CD_MODEL"),
	/**
	 * 注册码测试状态 1:未测试 2：测试通过 3：测试未通过
	 * */
	CD_REGISTERT_CODE_TEST_STATUS("CD_TEST_STATUS"), CD_REGISTERT_CODE_TEST_STATUS_CODE_NO(
			"1"), CD_REGISTERT_CODE_TEST_STATUS_CODE_SUCESS(
			"2"), CD_REGISTERT_CODE_TEST_STATUS_CODE_FAILED(
			"3"),
	/**
	 * 注册码激活状态 1:未激活 2：激活成功 3：激活失败
	 * */
	CD_REGISTERT_CODE_ACTIVE_STATUS("CD_ACTIVE_STATUS"), CD_REGISTERT_CODE_ACTIVE_STATUS_CODE_NO(
			"1"), CD_REGISTERT_CODE_ACTIVE_STATUS_CODE_SUCESS(
			"2"), CD_REGISTERT_CODE_ACTIVE_STATUS_CODE_FAILED(
			"3"),

	/**
	 * mac绑定状态. 1：未绑定 2：已绑定
	 */
	MAC_MANAGER_BIND_STATUS("MAC_BIND_STATUS"), MAC_MANAGER_BIND_STATUS_CODE_UNBIND(
			"1"), MAC_MANAGER_BIND_STATUS_CODE_BIND(
			"2"),

	/**
	 * 子系统类型.
	 * 
	 */
	SUB_SYSTEM("ZXT_TYPE"),

	/**
	 * 子系统在线状态.
	 * 
	 */
	SUB_SYSTEM_ONLINE_STATUS("SUB_SYS_ONLINE_STATUS"), SUB_SYSTEM_ONLINE_STATUS_CODE_UNKNOW(
			"0"), SUB_SYSTEM_ONLINE_STATUS_CODE_ONLINE(
			"1"), SUB_SYSTEM_ONLINE_STATUS_CODE_OFFLINE(
			"2"), SUB_SYSTEM_ONLINE_STATUS_CODE_FAULT(
			"3"),
	/**
	 * 设备生产厂商.
	 */
	CD_MANUAFACTURER("CD_MANUAFACTURER"),

	/**
	 * 设备在线状态.
	 */
	CD_ONLINE_STATUS("CD_ONLINE_STATUS"), CD_ONLINE_STATUS_CODE_ONLINE(
			"0"), CD_ONLINE_STATUS_CODE_OFFLINE(
			"1"), CD_ONLINE_STATUS_CODE_FAULT(
			"2"),

	/**
	 * 设备日志类型.
	 */
	CD_ONLINE_LOG("CD_ONLINE_LOG"), CD_ONLINE_LOG_CODE_ON("0"), CD_ONLINE_LOG_CODE_OFF(
			"1"),

	/**
	 * 软件更新状态.
	 */
	SOFTWARE_UPDATE_DETAILS("SOFTWARE_UPDATE_DETAILS"), SOFTWARE_UPDATE_DETAILS_NOT_UPDATE(
			"1"), SOFTWARE_UPDATE_DETAILS_ALREADY_UPDATE(
			"2"), SOFTWARE_UPDATE_DETAILS_CANCELED(
			"3"), SOFTWARE_UPDATE_DETAILS_OVERLAPED(
			"4"),SOFTWARE_UPDATE_DETAILS_DOWNLING("5"),
			SOFTWARE_UPDATE_DETAILS_INSTALLING("11"),
	SOFTWARE_UPDATE_DETAILS_DOWNFINISHED_INSTALL_BORDER("128"),
	/** 软件更新类型. */
	SOFTWARE_UPDATE_JOB_TYPE("SOFTWARE_UPDATE_JOB_TYPE"),SOFTWARE_UPDATE_JOB_TYPE_CD("1"),
	SOFTWARE_UPDATE_JOB_TYPE_TD("2"),
	
	/** 软件更新审核状态. */
	SOFTWARE_UPDATE_APPR_STATUS("SOFTWARE_UPDATE_APPR_STATUS"),SOFTWARE_UPDATE_APPR_STATUS_NO("1"),
	SOFTWARE_UPDATE_APPR_STATUS_SUCESS("2"),SOFTWARE_UPDATE_APPR_STATUS__FAIL("3"),
	

	/**
	 * 目标设备在线状态.
	 */
	TD_ONLINE_STATUS("TD_ONLINE_STATUS"), TD_ONLINE_STATUS_CODE_ONLINE(
					"0"), TD_ONLINE_STATUS_CODE_OFFLINE(
					"1"), 
	
	/**
	 * 数据长度单位.
	 */
	TD_REAL_DATA_LENGTH_UNIT("TD_REAL_DATA_LENGTH_UNIT"),
	/**
	 * 数据转义方式.
	 */
	TD_REAL_DATA_TRANSFER_METHOD("TD_REAL_DATA_TRANSFER_METHOD"),
	/**
	 * 数据大小端.
	 */
	TD_REAL_DATA_ENDIAN("TD_REAL_DATA_ENDIAN"),
	/**
	 * 目标设备实时数据类型.		
	 */
	TD_REAL_DATA_VALUE_TYPE("TD_REAL_DATA_VALUE_TYPE"),TD_REAL_DATA_VALUE_TYPE_UNSIGNED_INT("1"),
	TD_REAL_DATA_VALUE_TYPE_SIGNED_INT("2"),TD_REAL_DATA_VALUE_TYPE_BIT("3"),TD_REAL_DATA_VALUE_TYPE_STRING("4"),
	TD_REAL_DATA_VALUE_TYPE_ASCII("5"),TD_REAL_DATA_VALUE_TYPE_BCD("6"),
	
	/** 目标设备类型. */
	TD_TYPE("TD_TYPE"),TD_TYPE_CONTROLLER("0"),TD_TYPE_VIDEO("1"),
	TD_TYPE_AUTIO("2"),TD_TYPE_SCREEN("3"),TD_TYPE_GPS("4"),
	/**
	 * 文件类型
	 */
	MMS_FILE_TYPE("MMS_FILE_TYPE"), MMS_FILE_TYPE_SOFT("1"),
	/**
	 * 软件类型
	 */
	SOFT_TYPE("SOFT_TYPE"), SOFT_TYPE_B("1"), SOFT_TYPE_C(
			"2"),
	/**
	 * 审批状态
	 */
	APPROVAL_STATUS("APPROVAL_STATUS"), APPROVAL_STATUS_A("0"),APPROVAL_STATUS_B("1"), APPROVAL_STATUS_C(
					"2"),
	/**
	 * 审批类型
	 */
	APPROVAL_TYPE("APPROVAL_TYPE"), APPROVAL_TYPE_A("0"),APPROVAL_TYPE_B("1"),APPROVAL_TYPE_C("2"),
	/**
	 * 采集设备参数分隔符，key1：value1;key2:value2;
	 */
	CD_PARAMTER_SPLIT_KRY_VALUE(":"), CD_PARAMTER_SPLIT_PARAMETERS(";"),
	
	/** 采集设备业务类型.*/
	CD_BUSINESS_TYPE("CD_BUSINESS_TYPE"),CD_BUSINESS_TYPE_DEFAULT("0"),
	
	/** 用户程序类型 */
	USER_PROGRAM_TYPE("USER_PROGRAM_TYPE"),USER_PROGRAM_TYPE_A("AppUser"),USER_PROGRAM_TYPE_B("AppCollect"),
	
	/** 用户程序行业*/
	SOFT_BUSINESS_TYPE("SOFT_BUSINESS_TYPE"),SOFT_BUSINESS_TYPE_A("01"),SOFT_BUSINESS_TYPE_B("02"),SOFT_BUSINESS_TYPE_C("03"),SOFT_BUSINESS_TYPE_D("04"),
	SOFT_BUSINESS_TYPE_E("05"),SOFT_BUSINESS_TYPE_F("06"),SOFT_BUSINESS_TYPE_G("07"),SOFT_BUSINESS_TYPE_H("08"),SOFT_BUSINESS_TYPE_I("09"),SOFT_BUSINESS_TYPE_J("10"),SOFT_BUSINESS_TYPE_K("11"),SOFT_BUSINESS_TYPE_L("12"),SOFT_BUSINESS_TYPE_M("13"),
	
	/** 用户程序厂家编码*/
	/** 电梯厂家编码*/
	SOFT_BUSINESS_TYPE_01("SOFT_BUSINESS_TYPE_01"),SOFT_BUSINESS_TYPE_01_A("0001"),SOFT_BUSINESS_TYPE_01_B("0002"),SOFT_BUSINESS_TYPE_01_C("0003"),SOFT_BUSINESS_TYPE_01_D("0004"),
	SOFT_BUSINESS_TYPE_01_E("0005"),SOFT_BUSINESS_TYPE_01_F("0006"),SOFT_BUSINESS_TYPE_01_G("0007"),SOFT_BUSINESS_TYPE_01_H("0008"),SOFT_BUSINESS_TYPE_01_I("0009"),
	
	/** 空压机厂家编码*/
	SOFT_BUSINESS_TYPE_02("SOFT_BUSINESS_TYPE_02"),SOFT_BUSINESS_TYPE_02_A("0001"),SOFT_BUSINESS_TYPE_02_B("0002"),SOFT_BUSINESS_TYPE_02_C("0003"),
	
	/** 卷绕机厂家编码*/
	SOFT_BUSINESS_TYPE_03("SOFT_BUSINESS_TYPE_03"),SOFT_BUSINESS_TYPE_03_DEFAULT("0001"),
	
	/** 供热系统厂家编码*/
	SOFT_BUSINESS_TYPE_04("SOFT_BUSINESS_TYPE_04"),SOFT_BUSINESS_TYPE_04_DEFAULT("0001"),
	
	/** 充电桩厂家编码*/
	SOFT_BUSINESS_TYPE_05("SOFT_BUSINESS_TYPE_05"),SOFT_BUSINESS_TYPE_05_DEFAULT("0001"),
	
	/** 充电桩厂家编码*/
	SOFT_BUSINESS_TYPE_06("SOFT_BUSINESS_TYPE_06"),SOFT_BUSINESS_TYPE_06_DEFAULT("0001"),
	
	/** 塔机厂家编码*/
	SOFT_BUSINESS_TYPE_07("SOFT_BUSINESS_TYPE_07"),SOFT_BUSINESS_TYPE_07_DEFAULT("0001"),
	
	/** 挤出机厂家编码*/
	SOFT_BUSINESS_TYPE_08("SOFT_BUSINESS_TYPE_08"),SOFT_BUSINESS_TYPE_08_DEFAULT("0001"),
	
	/** 机器人厂家编码*/
	SOFT_BUSINESS_TYPE_09("SOFT_BUSINESS_TYPE_09"),SOFT_BUSINESS_TYPE_09_DEFAULT("0001"),
	
	/** 大传动厂家编码*/
	SOFT_BUSINESS_TYPE_10("SOFT_BUSINESS_TYPE_10"),SOFT_BUSINESS_TYPE_10_DEFAULT("0001"),
	
	/** 空调厂家编码*/
	SOFT_BUSINESS_TYPE_11("SOFT_BUSINESS_TYPE_11"),SOFT_BUSINESS_TYPE_11_DEFAULT("0001"),
	
	/** 锻压厂家编码*/
	SOFT_BUSINESS_TYPE_12("SOFT_BUSINESS_TYPE_12"),SOFT_BUSINESS_TYPE_12_DEFAULT("0001"),
	
	/** 生产厂家编码*/
	SOFT_BUSINESS_TYPE_13("SOFT_BUSINESS_TYPE_13"),SOFT_BUSINESS_TYPE_13_DEFAULT("0001"),
	
	/** SIM 卡 */
	SIM_NETWORK_TYPE("SIM_NETWORK_TYPE"),SIM_NETWORK_TYPE_2G("1"),
	SIM_NETWORK_TYPE_3G("2"),SIM_NETWORK_TYPE_4G("3"),
	
	/** 运营商 */
	TELECOMS_OPERATOR_TYPE("TELECOMS_OPERATOR_TYPE"),TELECOMS_OPERATOR_TYPE_UNION("1"),
	TELECOMS_OPERATOR_TYPE_MOBILE("2"),TELECOMS_OPERATOR_TYPE_TELECOM("3"),

	/**
	 * SIM绑定状态. 1：未绑定 2：已绑定
	 */
	SIM_MANAGER_BIND_STATUS("SIM_BIND_STATUS"), SIM_MANAGER_BIND_STATUS_CODE_UNBIND(
			"1"), SIM_MANAGER_BIND_STATUS_CODE_BIND(
			"2"),
	/**
	 * 子系统业务分类.
	 */
	SUB_SYS_BUSINESS("SUB_SYS_BUSINESS"),SUB_SYS_BUSINESS_PLATFORM("platform"),
	SUB_SYS_BUSINESS_APP("tdhsapp"),
	
	/**
	 * 设备参数配置
	 */
	CD_PARAMETERS("CD_PARAMETERS"),
	/**
	 * 设备运行状态
	 */
	CD_RUN_STATUS("CD_RUN_STATUS"),

	//FFFF
	TD_SAMPLE_PERIOD_REALDATA("65535"),TD_SAMPLE_PERIOD_FUNCTION_CODE("0"),
	
	SYS_SYNC_INFO_OPREATTION_ADD("1"),SYS_SYNC_INFO_OPREATTION_UPDATE("3"),
	SYS_SYNC_INFO_OPREATTION_DEL("2"),
	/**
	 * 数据格式  1.16进制 2.ASCII码
	 */
	TD_CONTROLLER_DATA_COMMNAD_LIB_FORMAT("COMMNAD_LIB_FORMAT"),
	TD_CONTROLLER_DATA_COMMNAD_LIB_FORMAT_16("1"),
	TD_CONTROLLER_DATA_COMMNAD_LIB_FORMAT_ASCII("2"),
	/** 
	 * 校验方式 1.CRC校验 2.和校验
	 */
	TD_CONTROLLER_DATA_COMMNAD_LIB_CHECK("COMMNAD_LIB_CHECK"),
	TD_CONTROLLER_DATA_COMMNAD_LIB_CHECK_CRC("1"),
	TD_CONTROLLER_DATA_COMMNAD_LIB_CHECK_AND("2"),
	
	/**
	 * 控制器厂家类型.
	 */
	TD_CONTROLLER_FACTORY_TYPE("TD_CONTROLLER_FACTORY_TYPE"),
	
	
	DEFAULT_DELIMITER(":"),

	DEFAULT_UNKNOWN("未知"),
	
	WEB_METHOD("LOGIN_USER"),
	
	IS_CANCEL_Y("Y"),
	
	Constant_util_version("1");
	
	
	
	
	
	
	
	public String value;

	StatusEnum(String value) {
		this.value = value;
	}

}
